### ISSUE TITLE
Cmake error "target_link_directories" Cmake command not found. Upgrade to tag 1.1.0

### ISSUE THREAD

**Issue by mrawding** [ros2-gbp/libyaml_vendor-release#4] opened 2021-02-17 16:42 UTC
Hello,

I see that the release was recently upgraded to 1.0.3-1 for foxy distro. However there is an error in there that does not check for CMake version 3.13 or less before calling target_link_directories. Thus, source installation of libyaml_vendor fails for foxy at that point. The master branch, foxy-backport branch, and tag 1.1.0 all include this check, which should fix that failure.

**Comment by clalancette** [comment] 2021-02-17 17:21
This is essentially a duplicate of https://github.com/ros2/libyaml_vendor/issues/33 , so closing it.  We need to get the fix onto the foxy branch first, then get a release done to get the changes out.

**Closed as completed by clalancette** 2021-02-17 17:21 UTC
